name: CI CD Pipeline

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ayushmartin/skills_streak_backend:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Write .env file from GitHub Secrets
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  pushToDockerHub:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  deployToEC2:
    needs: pushToDockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write .env file from GitHub Secrets
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy deployment files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yaml,.env,deploy.sh"
          target: "~/skills_streak"

      - name: Run deploy.sh on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/skills_streak
            chmod +x deploy.sh
            ./deploy.sh
